### ISSUE TITLE
Inverted SBUS

### ISSUE THREAD

**Issue by scooterwillis** [ljanyst/pipilot#1]
Can you clarify the inverted SBUS problem related to building an external inverter versus inverting in software and bit-banging an IO pin. 

For receiving data nice to have the inverter option to avoid polling.

**Comment by ljanyst** [comment]
You can obviously bit-bang whatever want. Including SBUS. There are some issues, though. Bit-banging at those speeds becomes tricky, if you cannot use some sort of a hardware synchronization. The easiest is to use hardware UART which you will likely need to invert in hardware. You also need to be careful about voltage levels.
