### ISSUE TITLE
Can't connect to web interface. 

### ISSUE THREAD

**Issue by decortealex** [ljanyst/pipilot#2]
I installed the library and ran the `pipilot -n pipilot` command on a Raspberry Pi Zero W. It runs without errors and 'opens' the web interface on port 5005. However, when I try to connect on my laptop through the Pi's IP address on port 5005, it fails to connect. Connecting on the Pi also fails. How can I resolve this issue?

**Comment by ljanyst** [comment]
I would run `sudo netstat -nlp | grep 5005` to see on what exactly happens with the listening socket. It's likely some sort of IPv6 vs IPv4 issue or a firewall setting.
